# Site settings
title: Bienvenido a Mi blog
email: gaforeror@gmail.com
email: giaforeroro@unal.edu.co
description: > # this means to ignore newlines until "baseurl:"
 Este sitio comienza como una idea de software libre, en la cual espero hablar sobre mis proyectos interes y crear algunos comentarios de discusion sobre algunas noticas que leo de otras paginas
baseurl: "/personal"
url: "https://gaforeror.github.io"
twitter_username: gaforeror
github_username:  gaforeror
facebook_username: Aldo.corrales
# Build settings
markdown: kramdown
